# Generated by Django 4.0.6 on 2022-09-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
