# Generated by Django 4.0.6 on 2022-09-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_participant_participant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='prize_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='prize_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='prize_3',
            field=models.IntegerField(null=True),
        ),
    ]
