# Generated by Django 4.0.6 on 2022-09-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_participant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.TextField(default='assets/images/cat.svg'),
            preserve_default=False,
        ),
    ]
