# Generated by Django 4.0.6 on 2022-09-19 18:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_rename_eligible_gender_event_eligible_genders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='accepted_formats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TIFF', 'TIFF'), ('JPEG', 'JPEG'), ('PNG', 'PNG'), ('JPG', 'JPG')], max_length=10), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
