# Generated by Django 4.0.6 on 2022-09-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Anna Auditorium', max_length=128),
            preserve_default=False,
        ),
    ]
