# Generated by Django 4.0.6 on 2022-09-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='excel_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='file_submission',
            field=models.BooleanField(default=False),
        ),
    ]
