# Generated by Django 4.0.6 on 2022-09-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_alter_event_accepted_formats_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
