# Generated by Django 4.0.6 on 2022-09-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_user_had_food_user_payment_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reg_no',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
