# Generated by Django 4.0.6 on 2022-09-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='had_food',
            field=models.BooleanField(default=False),
        ),
    ]
