# Generated by Django 4.0.6 on 2022-09-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_registration_had_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='id',
        ),
        migrations.AlterField(
            model_name='registration',
            name='receipt',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
